name: Container Workflow

on:
  workflow_call:
    inputs:
      image-tag:
        type: string

permissions:
  contents: write
  checks: write
  packages: write

env:
  REGISTRY: "ghcr.io"

jobs:
  container:
    name: Build Docker Image
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download application binary
      uses: actions/download-artifact@v3
      with:
        name: app
        path: target

    - name: Log in to the Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{  env.REGISTRY }}/${{ github.repository }}:${{ inputs.image-tag }}
